[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[cargo-new]
vcs = "none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27.5"
env_logger = "0.9.3"
log = "0.4.17"
wgpu = "0.14.0"
