[package]
name = "app"
version = "0.1.0"
edition = "2021"

[cargo-new]
vcs = "none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { path = "../engine" }
pollster = "0.2.5"
